param_dir: '/app/data/Frames'
gram_directory: '/app/data/grams/normalised'
importance_path: '/app/data/feature_importance'
prefiltered_gram_path: '/app/data/grams/prefiltered_concat'
index_path: '/app/data/index.csv'

batch_size: 128
input_size: 2500
output_size: 41

max_epochs: 10000

splits: [0.8, 0.1, 0.1]

loss_fn: 'msle'
msle_log_part: 20


optimiser_setup:
    optimiser: 'adam'
    lr: 0.001

    use_scheduler: True
    scheduler: 'stepLR'

    step_size: 100
    gamma: 1

    interval: 'epoch'
    frequency: 1
    monitor: 'val_msle_loss'
